# Mandatory configs
#input: ["in1", "in2"]             # replace values
input: ["img", "bboxes"]             # replace values
output: ["bbox_scores", "bbox_labels"]  # replace values

# Optional configs depending on node
threshold: 0.5                    # example





# # Mandatory configs
# #input: ["in1", "in2"]             # replace values
# input: ["img", "bboxes"]             # replace values
# output: ["bboxes", "bbox_scores", "bbox_labels"]  # replace values
# 
# # Optional configs depending on node
# threshold: 0.5                    # example
 
